# Generated by Django 3.2 on 2021-04-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='music',
            name='song',
            field=models.TextField(default='song', verbose_name='名稱'),
        ),
    ]
