# Generated by Django 3.2 on 2021-04-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210413_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
